// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CTPH_CoreData.Models
{
    public partial class Elementos_Listas_Valores
    {
        public Elementos_Listas_Valores()
        {
            SituacionAmbiente_Elementos = new HashSet<SituacionAmbiente_Elementos>();
        }

        [Key]
        public int idListaValores { get; set; }
        public int? idElemento { get; set; }
        [StringLength(55)]
        public string NombreListaValor { get; set; }

        [ForeignKey(nameof(idElemento))]
        [InverseProperty(nameof(Elementos.Elementos_Listas_Valores))]
        public virtual Elementos idElementoNavigation { get; set; }
        [InverseProperty("idListaValorNavigation")]
        public virtual ICollection<SituacionAmbiente_Elementos> SituacionAmbiente_Elementos { get; set; }
    }
}