// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CTPH_CoreData.Models
{
    public partial class Elementos
    {
        public Elementos()
        {
            Elementos_Listas_Valores = new HashSet<Elementos_Listas_Valores>();
            Perfil_Elementos = new HashSet<Perfil_Elementos>();
            SituacionAmbiente_Elementos = new HashSet<SituacionAmbiente_Elementos>();
        }

        [Key]
        public int idElemento { get; set; }
        [Required]
        [StringLength(55)]
        public string Elemento { get; set; }
        public byte idTipoValor { get; set; }

        [ForeignKey(nameof(idTipoValor))]
        [InverseProperty(nameof(Tipos_Valores.Elementos))]
        public virtual Tipos_Valores idTipoValorNavigation { get; set; }
        [InverseProperty("idElementoNavigation")]
        public virtual ICollection<Elementos_Listas_Valores> Elementos_Listas_Valores { get; set; }
        [InverseProperty("idElementoNavigation")]
        public virtual ICollection<Perfil_Elementos> Perfil_Elementos { get; set; }
        [InverseProperty("idElementoNavigation")]
        public virtual ICollection<SituacionAmbiente_Elementos> SituacionAmbiente_Elementos { get; set; }
    }
}