// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CTPH_CoreData.Models
{
    public partial class Muestras
    {
        public Muestras()
        {
            Muestras_Valores = new HashSet<Muestras_Valores>();
        }

        [Key]
        public long idMuestra { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime fhMuestra { get; set; }
        [StringLength(55)]
        public string Observaciones { get; set; }
        public long? idSituacionAmbiente { get; set; }

        [ForeignKey(nameof(idSituacionAmbiente))]
        [InverseProperty(nameof(SituacionAmbiente.Muestras))]
        public virtual SituacionAmbiente idSituacionAmbienteNavigation { get; set; }
        [InverseProperty("idMuestraNavigation")]
        public virtual ICollection<Muestras_Valores> Muestras_Valores { get; set; }
    }
}