// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CTPH_CoreData.Models
{
    public partial class Muestras_Valores
    {
        [Key]
        public long idMuestra { get; set; }
        [Key]
        public int idPuntoDeMedida { get; set; }
        [Column(TypeName = "decimal(4, 2)")]
        public decimal? Temperatura { get; set; }
        public byte? Humedad { get; set; }

        [ForeignKey(nameof(idMuestra))]
        [InverseProperty(nameof(Muestras.Muestras_Valores))]
        public virtual Muestras idMuestraNavigation { get; set; }
        [ForeignKey(nameof(idPuntoDeMedida))]
        [InverseProperty(nameof(PuntosDeMedida.Muestras_Valores))]
        public virtual PuntosDeMedida idPuntoDeMedidaNavigation { get; set; }
    }
}