// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CTPH_CoreData.Models
{
    public partial class Perfiles
    {
        public Perfiles()
        {
            Perfil_Elementos = new HashSet<Perfil_Elementos>();
        }

        [Key]
        public int idPerfil { get; set; }
        [StringLength(55)]
        public string Perfil { get; set; }

        [InverseProperty("idPerfilNavigation")]
        public virtual ICollection<Perfil_Elementos> Perfil_Elementos { get; set; }
    }
}