// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CTPH_CoreData.Models
{
    public partial class Perfil_Elementos
    {
        [Key]
        public int idPerfil { get; set; }
        [Key]
        public int idElemento { get; set; }
        public bool? Activo { get; set; }

        [ForeignKey(nameof(idElemento))]
        [InverseProperty(nameof(Elementos.Perfil_Elementos))]
        public virtual Elementos idElementoNavigation { get; set; }
        [ForeignKey(nameof(idPerfil))]
        [InverseProperty(nameof(Perfiles.Perfil_Elementos))]
        public virtual Perfiles idPerfilNavigation { get; set; }
    }
}