// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CTPH_CoreData.Models
{
    public partial class PuntosDeMedida
    {
        public PuntosDeMedida()
        {
            Muestras_Valores = new HashSet<Muestras_Valores>();
        }

        [Key]
        public int idPuntoDeMedida { get; set; }
        [StringLength(55)]
        public string Descripcion { get; set; }
        [StringLength(555)]
        public string Observaciones { get; set; }
        public byte? idTipoPuntoDeMedida { get; set; }

        [ForeignKey(nameof(idTipoPuntoDeMedida))]
        [InverseProperty(nameof(Tipos_PuntosDeMedida.PuntosDeMedida))]
        public virtual Tipos_PuntosDeMedida idTipoPuntoDeMedidaNavigation { get; set; }
        [InverseProperty("idPuntoDeMedidaNavigation")]
        public virtual ICollection<Muestras_Valores> Muestras_Valores { get; set; }
    }
}