// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CTPH_CoreData.Models
{
    public partial class SituacionAmbiente_Elementos
    {
        [Key]
        public long idSituacionAmbienteElementos { get; set; }
        [StringLength(255)]
        public string Valor { get; set; }
        public int? idListaValor { get; set; }
        public long idSituacionAmbiente { get; set; }
        public int idElemento { get; set; }

        [ForeignKey(nameof(idElemento))]
        [InverseProperty(nameof(Elementos.SituacionAmbiente_Elementos))]
        public virtual Elementos idElementoNavigation { get; set; }
        [ForeignKey(nameof(idListaValor))]
        [InverseProperty(nameof(Elementos_Listas_Valores.SituacionAmbiente_Elementos))]
        public virtual Elementos_Listas_Valores idListaValorNavigation { get; set; }
        [ForeignKey(nameof(idSituacionAmbiente))]
        [InverseProperty(nameof(SituacionAmbiente.SituacionAmbiente_Elementos))]
        public virtual SituacionAmbiente idSituacionAmbienteNavigation { get; set; }
    }
}