// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CTPH_CoreData.Models
{
    public partial class Tipos_PuntosDeMedida
    {
        public Tipos_PuntosDeMedida()
        {
            PuntosDeMedida = new HashSet<PuntosDeMedida>();
        }

        [Key]
        public byte idTipoPuntoDeMedida { get; set; }
        [StringLength(55)]
        public string Descripcion { get; set; }

        [InverseProperty("idTipoPuntoDeMedidaNavigation")]
        public virtual ICollection<PuntosDeMedida> PuntosDeMedida { get; set; }
    }
}